# -*- coding: utf-8 -*-
"""Introdução ao Panda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDpzVlmKmWWevVWMLeH47RrjJrFouxz9
"""

import pandas as pd

dados_frutas ={"Maça":[30],'Banana':[20]}
frutas = pd.DataFrame(data=dados_frutas);
print(frutas);

dados_vendas={"Maça": [1000,5000], 'Banana': [700,2000]}
ano_vendas= {'Vendas de 2022', 'Vendas de 2023'}

vendas_frutas = pd.DataFrame(data=dados_vendas, index=list(ano_vendas))
print (vendas_frutas)

print("----------------------------------------------------------------\n")


corona = pd.read_csv("corona.csv", header=0)
print(corona.head())
print("----------------------------------------------------------------\n")
print(corona.dtypes)
print("----------------------------------------------------------------\n")

coluna_espicifica = corona['Country/Region']
print(coluna_espicifica)
print("----------------------------------------------------------------\n")

valor_maximo = corona['Deaths'].max()
print(valor_maximo)
print("----------------------------------------------------------------\n")

valor_determinado = corona[corona['Deaths'] == 330]
print(valor_determinado)